# Generated by Django 4.1.6 on 2023-04-30 21:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CL', '0002_cancel_request_clients_clprofile_clrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EM', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprofiles',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='emprofiles',
            name='user',
        ),
        migrations.AlterField(
            model_name='emprofiles',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emprofiles',
            name='domain',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emprofiles',
            name='service_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 30, 21, 28, 24, 675473), null=True)),
                ('service_mul_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.mul_clrequest')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.clrequest')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EM.technicians')),
            ],
        ),
        migrations.CreateModel(
            name='CancelReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_reply', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 30, 21, 28, 24, 675473), null=True)),
                ('reason', models.TextField(max_length=500)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.clients')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EM.technicians')),
            ],
        ),
        migrations.AddField(
            model_name='emprofiles',
            name='em',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EM.technicians'),
        ),
    ]
