# Generated by Django 4.1.6 on 2023-05-02 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0012_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='em_history',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EM.technicians'),
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 13, 12, 3, 945246), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 13, 12, 3, 945246), null=True),
        ),
    ]
