# Generated by Django 4.1.6 on 2023-05-02 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0013_em_history_technician_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='em_history',
            name='technician',
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 13, 18, 21, 581457), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 13, 18, 21, 581457), null=True),
        ),
    ]
