# Generated by Django 4.1.6 on 2023-05-02 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_reg_phone'),
        ('EM', '0015_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicians',
            name='tech_reg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tech_reg'),
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 18, 5, 2, 182630), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 18, 5, 2, 182630), null=True),
        ),
    ]
