# Generated by Django 4.1.6 on 2023-05-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0016_technicians_tech_reg_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicians',
            name='tech_reg',
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 18, 13, 37, 775182), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 18, 13, 37, 775182), null=True),
        ),
    ]
