# Generated by Django 4.1.6 on 2023-05-05 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CL', '0018_alter_cancel_request_date_alter_clrequest_created_at_and_more'),
        ('EM', '0017_remove_technicians_tech_reg_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 11, 22, 26, 688115), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 11, 22, 26, 688115), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='service_mul_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_replies', to='CL.mul_clrequest'),
        ),
    ]
