# Generated by Django 4.1.6 on 2023-05-08 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0021_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprofiles',
            name='service_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 10, 3, 40, 874926), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 10, 3, 40, 874926), null=True),
        ),
    ]
