# Generated by Django 4.1.6 on 2023-05-08 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0025_alter_cancelreply_date_alter_emprofiles_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 11, 29, 5, 191853), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 11, 29, 5, 191853), null=True),
        ),
    ]
