# Generated by Django 4.1.6 on 2023-05-08 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0027_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 14, 26, 58, 631032), null=True),
        ),
        migrations.RemoveField(
            model_name='emprofiles',
            name='domain',
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 14, 26, 58, 631032), null=True),
        ),
        migrations.AddField(
            model_name='emprofiles',
            name='domain',
            field=models.ManyToManyField(to='EM.servicedomain'),
        ),
    ]
