# Generated by Django 4.1.6 on 2023-05-08 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0028_servicedomain_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceDomain',
            new_name='ServiceDevice',
        ),
        migrations.RenameField(
            model_name='emprofiles',
            old_name='domain',
            new_name='service_devices',
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 14, 50, 21, 800053), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 14, 50, 21, 800053), null=True),
        ),
    ]
