# Generated by Django 4.1.6 on 2023-05-08 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0029_rename_servicedomain_servicedevice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprofiles',
            name='service_devices',
        ),
        migrations.AddField(
            model_name='emprofiles',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 15, 11, 8, 42404), null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 8, 15, 11, 8, 42404), null=True),
        ),
        migrations.DeleteModel(
            name='ServiceDevice',
        ),
    ]
