# Generated by Django 4.1.6 on 2023-05-23 07:52

import datetime
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('EM', '0038_alter_cancelreply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelreply',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 7, 52, 28, 318499), null=True),
        ),
        migrations.AlterField(
            model_name='emprofiles',
            name='service_place',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='technicianreply',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 23, 7, 52, 28, 318499), null=True),
        ),
    ]
