# Generated by Django 4.1.6 on 2023-05-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tech_reg_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
