# Generated by Django 4.1.6 on 2023-05-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Client',
            new_name='Cl_reg',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='technian',
            new_name='tech_reg',
        ),
    ]
