# Generated by Django 4.1.6 on 2023-05-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_admin_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_reg',
        ),
    ]
