# Generated by Django 4.1.6 on 2023-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_admin_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_reg',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tech_reg',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tech_reg',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tech_reg',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
