# Generated by Django 4.1.6 on 2023-05-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_user_reg_email_user_reg_first_name_user_reg_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='techReg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tech_reg'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='userReg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user_reg'),
        ),
    ]
