# Generated by Django 4.1.6 on 2023-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_usertype_techreg_usertype_userreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_reg',
            name='id_proof_number',
            field=models.CharField(max_length=100),
        ),
    ]
