# Generated by Django 4.1.6 on 2023-06-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_tech_reg_id_proof_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_reg',
            name='experience',
        ),
    ]
