# Generated by Django 4.1.6 on 2023-03-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cl_edit_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_profile', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('cl_address', models.CharField(max_length=200)),
            ],
        ),
    ]
