# Generated by Django 4.1.6 on 2023-04-30 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_request', models.IntegerField(blank=True, null=True)),
                ('cl_mul_request', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 30, 21, 28, 24, 673473), null=True)),
                ('reason', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='clprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_profile', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('cl_address', models.TextField(max_length=500)),
                ('service_place', models.CharField(blank=True, default='None', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_address', models.TextField(max_length=200)),
                ('complaint', models.TextField(max_length=200)),
                ('device_image', models.ImageField(default='default.jpg', upload_to='device_pics')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 30, 21, 28, 24, 673473), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mul_clrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_address', models.TextField(max_length=200)),
                ('complaint', models.TextField(max_length=200)),
                ('device_image', models.ImageField(default='default.jpg', upload_to='device_pics')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 30, 21, 28, 24, 673473), null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('request_status', models.CharField(blank=True, default='pending', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.clients')),
            ],
        ),
        migrations.DeleteModel(
            name='cl_edit_profile',
        ),
    ]
