# Generated by Django 4.1.6 on 2023-05-05 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CL', '0018_alter_cancel_request_date_alter_clrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel_request',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 23, 4, 30, 791250), null=True),
        ),
        migrations.AlterField(
            model_name='clrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 23, 4, 30, 791250), null=True),
        ),
        migrations.AlterField(
            model_name='mul_clrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 23, 4, 30, 791250), null=True),
        ),
        migrations.CreateModel(
            name='cl_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.cancel_request')),
                ('service_mul_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.mul_clrequest')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CL.clrequest')),
            ],
        ),
    ]
