# Generated by Django 4.1.6 on 2023-05-31 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CL', '0043_alter_cancel_request_date_alter_clrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel_request',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 31, 20, 9, 53, 324463), null=True),
        ),
        migrations.AlterField(
            model_name='clrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 31, 20, 9, 53, 324463), null=True),
        ),
        migrations.AlterField(
            model_name='clrequest',
            name='request_status',
            field=models.CharField(blank=True, default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mul_clrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 31, 20, 9, 53, 324463), null=True),
        ),
    ]
